package com.streetsaarthi.models
import android.os.Parcelable
import kotlinx.parcelize.IgnoredOnParcel
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue
@Parcelize
data class Item(
    val allow_forking: Boolean,
    @IgnoredOnParcel val archive_url: String? = null,
    val archived: Boolean,
    @IgnoredOnParcel val assignees_url: String? = null,
    @IgnoredOnParcel val blobs_url: String? = null,
    @IgnoredOnParcel val branches_url: String? = null,
    @IgnoredOnParcel val clone_url: String? = null,
    @IgnoredOnParcel  val collaborators_url: String? = null,
    @IgnoredOnParcel val comments_url: String? = null,
    @IgnoredOnParcel val commits_url: String? = null,
    @IgnoredOnParcel val compare_url: String? = null,
    @IgnoredOnParcel val contents_url: String? = null,
    @IgnoredOnParcel val contributors_url: String? = null,
    @IgnoredOnParcel val created_at: String? = null,
    @IgnoredOnParcel val default_branch: String? = null,
    @IgnoredOnParcel val deployments_url: String? = null,
    @IgnoredOnParcel val description: String? = null,
    val disabled: Boolean,
    @IgnoredOnParcel val downloads_url: String? = null,
    @IgnoredOnParcel val events_url: String? = null,
    val fork: Boolean,
    val forks: Int,
    val forks_count: Int,
    @IgnoredOnParcel val forks_url: String? = null,
    @IgnoredOnParcel val full_name: String? = null,
    @IgnoredOnParcel val git_commits_url: String? = null,
    @IgnoredOnParcel val git_refs_url: String? = null,
    @IgnoredOnParcel val git_tags_url: String? = null,
    @IgnoredOnParcel val git_url: String? = null,
    val has_discussions: Boolean,
    val has_downloads: Boolean,
    val has_issues: Boolean,
    val has_pages: Boolean,
    val has_projects: Boolean,
    val has_wiki: Boolean,
    @IgnoredOnParcel val homepage: String? = null,
    @IgnoredOnParcel val hooks_url: String? = null,
    @IgnoredOnParcel val html_url: String? = null,
    val id: Int,
    val is_template: Boolean,
    @IgnoredOnParcel val issue_comment_url: String? = null,
    @IgnoredOnParcel val issue_events_url: String? = null,
    @IgnoredOnParcel val issues_url: String? = null,
    @IgnoredOnParcel val keys_url: String? = null,
    @IgnoredOnParcel val labels_url: String? = null,
    @IgnoredOnParcel val language: String? = null,
    @IgnoredOnParcel val languages_url: String? = null,
    @IgnoredOnParcel val merges_url: String? = null,
    @IgnoredOnParcel val milestones_url: String? = null,
    @IgnoredOnParcel val name: String? = null,
    @IgnoredOnParcel val node_id: String? = null,
    @IgnoredOnParcel val notifications_url: String? = null,
    val open_issues: Int,
    val open_issues_count: Int,
    @IgnoredOnParcel val owner: @RawValue Owner,
    val private : Boolean,
    @IgnoredOnParcel val pulls_url: String? = null,
    @IgnoredOnParcel val pushed_at: String? = null,
    @IgnoredOnParcel val releases_url: String? = null,
    val score: Double,
    val size: Int,
    @IgnoredOnParcel val ssh_url: String? = null,
    val stargazers_count: Int,
    @IgnoredOnParcel val stargazers_url: String? = null,
    @IgnoredOnParcel val statuses_url: String? = null,
    @IgnoredOnParcel val subscribers_url: String? = null,
    @IgnoredOnParcel val subscription_url: String? = null,
    @IgnoredOnParcel val svn_url: String? = null,
    @IgnoredOnParcel val tags_url: String? = null,
    @IgnoredOnParcel val teams_url: String? = null,
    @IgnoredOnParcel val trees_url: String? = null,
    @IgnoredOnParcel val updated_at: String? = null,
    @IgnoredOnParcel val url: String? = null,
    @IgnoredOnParcel val visibility: String? = null,
    val watchers: Int,
    val watchers_count: Int,
    val web_commit_signoff_required: Boolean
): Parcelable